gg.jte.development-mode=true
spring.application.name=chat-webflux

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.threads.virtual.enabled=true

spring.docker.compose.lifecycle-management=start_only