gg.jte.development-mode=true
spring.application.name=chat-webflux
spring.threads.virtual.enabled=true

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

spring.ai.vectorstore.redis.initialize-schema=true
spring.ai.vectorstore.redis.index-name=spring-ai-index
spring.ai.vectorstore.redis.prefix=embedding:

spring.ai.mcp.client.name=${spring.application.name}
spring.ai.mcp.client.type=async
spring.ai.mcp.client.sse.connections.mcp-server-webflux.url=http://localhost:8081

spring.docker.compose.lifecycle-management=start_only